---
name: Perl-Critic-More
version: 0.1
author:
  - 'Chris Dolan <cdolan@cpan.org>'
abstract: Supplemental policies for Perl::Critic
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  PPI: 0.19901
  Perl::Critic: 0.21
build_requires:
  Test::More: 0
provides:
  Perl::Critic::More:
    file: lib/Perl/Critic/More.pm
    version: 0.1
  Perl::Critic::Policy::Editor::RequireEmacsFileVariables:
    file: lib/Perl/Critic/Policy/Editor/RequireEmacsFileVariables.pm
    version: 0.1
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
