---
name: Perl-Critic-More
version: 1.000
author:
  - 'Chris Dolan <cdolan@cpan.org>'
abstract: Supplemental policies for Perl::Critic
license: perl
resources:
  MailingList: http://perlcritic.tigris.org/servlets/SummarizeList?listName=users
  Repository: http://perlcritic.tigris.org/svn/perlcritic/trunk/Perl-Critic-More/
  homepage: http://perlcritic.com
  license: http://dev.perl.org/licenses/
requires:
  Perl::Critic: 1.082
  Readonly: 1.03
build_requires:
  Test::More: 0
recommends:
  Perl::MinimumVersion: 0.14
dynamic_config: 1
provides:
  Perl::Critic::More:
    file: lib/Perl/Critic/More.pm
    version: 1.000
  Perl::Critic::Policy::CodeLayout::RequireASCII:
    file: lib/Perl/Critic/Policy/CodeLayout/RequireASCII.pm
    version: 1.000
  Perl::Critic::Policy::Editor::RequireEmacsFileVariables:
    file: lib/Perl/Critic/Policy/Editor/RequireEmacsFileVariables.pm
    version: 1.000
  Perl::Critic::Policy::ErrorHandling::RequireUseOfExceptions:
    file: lib/Perl/Critic/Policy/ErrorHandling/RequireUseOfExceptions.pm
    version: 1.000
  Perl::Critic::Policy::Modules::PerlMinimumVersion:
    file: lib/Perl/Critic/Policy/Modules/PerlMinimumVersion.pm
    version: 1.000
  Perl::Critic::Policy::Modules::RequirePerlVersion:
    file: lib/Perl/Critic/Policy/Modules/RequirePerlVersion.pm
    version: 1.000
  Perl::Critic::Policy::ValuesAndExpressions::RestrictLongStrings:
    file: lib/Perl/Critic/Policy/ValuesAndExpressions/RestrictLongStrings.pm
    version: 1.000
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
