---
abstract: 'Supplemental policies for Perl::Critic'
author:
  - 'Chris Dolan <cdolan@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl-Critic-More
no_index:
  directory:
    - xt
  file:
    - TODO.pod
provides:
  Perl::Critic::More:
    file: lib/Perl/Critic/More.pm
    version: 1.003
  Perl::Critic::Policy::CodeLayout::RequireASCII:
    file: lib/Perl/Critic/Policy/CodeLayout/RequireASCII.pm
    version: 1.003
  Perl::Critic::Policy::Editor::RequireEmacsFileVariables:
    file: lib/Perl/Critic/Policy/Editor/RequireEmacsFileVariables.pm
    version: 1.003
  Perl::Critic::Policy::ErrorHandling::RequireUseOfExceptions:
    file: lib/Perl/Critic/Policy/ErrorHandling/RequireUseOfExceptions.pm
    version: 1.003
  Perl::Critic::Policy::Modules::PerlMinimumVersion:
    file: lib/Perl/Critic/Policy/Modules/PerlMinimumVersion.pm
    version: 1.003
  Perl::Critic::Policy::Modules::RequirePerlVersion:
    file: lib/Perl/Critic/Policy/Modules/RequirePerlVersion.pm
    version: 1.003
  Perl::Critic::Policy::ValuesAndExpressions::RequireConstantOnLeftSideOfEquality:
    file: lib/Perl/Critic/Policy/ValuesAndExpressions/RequireConstantOnLeftSideOfEquality.pm
    version: 1.003
  Perl::Critic::Policy::ValuesAndExpressions::RestrictLongStrings:
    file: lib/Perl/Critic/Policy/ValuesAndExpressions/RestrictLongStrings.pm
    version: 1.003
recommends:
  Perl::MinimumVersion: 0.14
requires:
  Perl::Critic: 1.098
  Readonly: 1.03
resources:
  MailingList: http://perlcritic.tigris.org/servlets/SummarizeList?listName=users
  homepage: http://perlcritic.com
  license: http://dev.perl.org/licenses/
  repository: http://guest@perlcritic.tigris.org/svn/perlcritic/trunk/distributions/Perl-Critic-More/
version: 1.003
